---
- become: true
  become_user: "{{cops_zope_vars.user}}"
  block:
  - stat: {path: "{{cops_zope_vars.py_root}}/bin/python"}
    register: venvexists
  # test if venv is usable, or redo it
  - when: venvexists.stat.exists
    shell: |-
      set -e
      {{cops_zope_vars.py_root}}/bin/python -c "from pip import main"
    register: testpyusable
    failed_when: false
  - when: 'venvexists.stat.exists and testpyusable.rc != 0'
    block:
    - file:
        state: absent
        path: "{{cops_zope_vars.py_root}}"
    - shell: |-
        set -e
        {% set d = cops_zope_vars.eggs_directory %}
        if [ -e "{{d}}" ];then
          cd "{{d}}"
          rm -rfv *linux-x86_64.egg
        fi
  - pip:
      name: "{{cops_zope_vars.venv_eggs}}"
      state: present
      virtualenv: "{{cops_zope_vars.py_root}}"
      virtualenv_python: "{{(
        (cops_zope_vars.build_py and
        '{0}/bin/python'.format(cops_zope_vars.py_inst)) or
        cops_zope_vars.get('orig_py', None) or
        '/usr/bin/python{0}'.format(cops_zope_vars.py_ver))}}"
      virtualenv_command: "{{(
        cops_zope_vars.build_py and
        '{0}/bin/virtualenv'.format(cops_zope_vars.py_inst) or
        cops_zope_vars.get('venv_bin', 'virtualenv'))}}"
      virtualenv_site_packages: "{{cops_zope_vars.venv_site_packages}}"
