---
- become: true
  become_user: "{{cops_zope_vars.user}}"
  block:
  - tags: [cops_zope_s_setup_buildout_bootstrap]
    when: [cops_zope_s_setup_buildout_bootstrap]
    block:
      - include_tasks: _setup_venv_eggs.yml
      - shell: |-
          set -ex
          {% set d = cops_zope_vars %}
          cd {{d.buildout_cwd}}
          {{d.py}} {{d.buildout_bootstrap}} {{d.buildout_bootstrap_args}}
        changed_when: false
  - tags: [cops_zope_s_setup_buildout_buildout]
    when: [cops_zope_s_setup_buildout_buildout]
    block:
      - shell: |-
          set -ex
          {% set d = cops_zope_vars %}
          cd {{d.buildout_cwd}}
          {{d.buildout_cmd}} {{d.buildout_args}}
        changed_when: false
  - tags: [cops_zope_s_setup_buildout_up]
    when: [cops_zope_s_setup_buildout_up]
    block:
      - shell: |-
          set -ex
          {% set d = cops_zope_vars %}
          cd {{d.buildout_cwd}}
          {{d.buildout_develop_up}}
        changed_when: false
