---
# copy this file instead of symlinking
cops_app_name: zopeproject
#
cops_zope_yarn_extra_steps: []
# cops_zope_nginx_content_template: "{nginx_content_headless_template}"
# cops_zope_lifecycle_haproxy: true
# cops_zope_nginx_content_template: "{{vars['cops_zope_nginx_content_headless_template']}}"
cops_zope_lifecycle_haproxy: true
cops_gis_packages:
- gdal-bin
- libgdal1-dev
- libgeos-dev
- geoip-bin
- libgeoip-dev
# __default come from the cops_registry voodoo (duplicated_defaults in main.yml)
# cops_zope_deb_packages: "{{vars['cops_zope_deb_runtime_packages']+vars['cops_zope_deb_gis_packages']}}"
# user/password in secret vault !
cops_zope_overrides_buildout_secret: {}
cops_zope_overrides_buildout:
  v:
    mailinglogger-to: "myapp-list@lists.foo.com"
