---
cops_app_name: zope
cops_zope_zope_profile: "{{cops_app_name}}"
#
zope_servers: zope_servers
app_servers: "{{zope_servers}}"
cops_installer_mode: lazy
cops_zope_name: "{{cops_app_name}}"
cops_zope_servers_ips: [127.0.0.1]
cops_zope_nginx_port: 180
cops_zope_nginx_ssl_port: 1443
corpusops_haproxy_registrations_registrations_zope:
  - hosts: ["{{cops_zope_domain}}"]
    ip: "{{cops_zope_servers_ips}}"
    frontends:
      80:
        to_port: "{{cops_zope_http_port}}"
      443:
        to_port: "{{cops_zope_http_port}}"
        ssl_terminated: true
        http_fallback: false
# vim:set ft=sls:
