---
cops_app_name: zope
cops_zope_zope_profile: "{{cops_app_name}}"
#
zope_servers: zope_servers
haproxy_servers: haproxy_servers
app_servers: "{{zope_servers}}"
cops_installer_mode: lazy
cops_zope_name: "{{cops_app_name}}"
cops_zope_servers_ips: [127.0.0.1]
cops_zope_nginx_port: 180
cops_zope_nginx_ssl_port: 1443
corpusops_nginx_default_vhost_port: "{{cops_zope_nginx_port}}"
corpusops_nginx_default_vhost_ssl_port: "{{cops_zope_nginx_ssl_port}}"
# set this to false to explicitly configure haproxy !
cops_zope_dynamic_haproxy: true
# manual conf (ignored when dynamic proxy)
corpusops_haproxy_registrations_registrations_zope:
  - regexes: [".*"]
    ip: "{{cops_zope_servers_ips}}"
    frontends:
      80:
        to_port: "{{cops_zope_nginx_port}}"
      443:
        to_port: "{{cops_zope_nginx_port}}"
        ssl_terminated: true
# vim:set ft=sls:
