---
- tags: ["cops_zope_lifecycle_app_push_code"]
  when: ["cops_zope_lifecycle_app_push_code"]
  become: "{{cops_zope_vars.become}}"
  block:
  - include_role: {name: zope_users, allow_duplicates: false}
  - assert:
      that: ["vars.get(varitem, none) is not none"]
      msg: "{{varitem}} must be set"
    loop_control: {loop_var: varitem}
    loop: [cops_cwd]
  - include_role: {name: corpusops.roles/utils/push_code}
    loop_control: {loop_var: _cops_provision_push_code}
    loop: "{{cops_zope_vars.push_codes}}"

