---
- include_role: {name: zope_vars,  allow_duplicates: false}
- when:
  - (cops_zope_lifecycle_haproxy|default(false))
  - (cops_zope_dynamic_haproxy|default(false))
  block:
  - setup: {}
  - name: compute haproxy backends
    include_jinja_vars:
      content: |
        ---
        {% set ret = [] %}
        {% for i in vars.groups.get('zope_servers', vars.groups.all) %}
        {%  set _ = ret.append((hostvars[i]).ansible_default_ipv4.address) %}
        {% endfor %}
        cops_zope_servers_ips: {{ ret | to_json }}
        corpusops_haproxy_registrations_registrations_dzope:
        - regexes: [".*"]
          ip: {{ret | to_json}}
          frontends:
            80:
              to_port: "{{cops_zope_nginx_port}}"
            443:
              to_port: "{{cops_zope_nginx_port}}"
              ssl_terminated: true
- set_fact:
    cacheable: false
    cops_zope_lifecycle_haproxy: "{{(
       (not vars.get('SKIP_INSTALL_HAPROXY', False)) and
       cops_zope_lifecycle_haproxy|default(false) or
       vars.get('FORCE_INSTALL_HAPROXY', False)
      )}}"
