---
- include_jinja_vars:
    content: |-
      {% set r = {} %}
      {% set _ = r.update({'only_steps': only_steps|default(False)}) %}
      {% set only_steps = r['only_steps'] %}
      #
      {% set _ = r.update({'cops_zope_s_docker_reconfigure': cops_zope_s_docker_reconfigure|default(False)}) %}
      {% set cops_zope_s_docker_reconfigure = r['cops_zope_s_docker_reconfigure'] %}
      #
      {% set _ = r.update({'cops_zope_lifecycle_app_push_code':         cops_zope_lifecycle_app_push_code|default(not only_steps)}) %}
      {% set cops_zope_lifecycle_app_push_code = r['cops_zope_lifecycle_app_push_code'] %}
      #
      {% set _ = r.update({'cops_zope_lifecycle_haproxy_reload':        cops_zope_lifecycle_haproxy_reload       |default(cops_zope_lifecycle_haproxy|default(not only_steps))}) %}
      {% set cops_zope_lifecycle_haproxy_reload = r['cops_zope_lifecycle_haproxy_reload'] %}
      #
      {% set _ = r.update({'cops_zope_lifecycle_haproxy_config':        cops_zope_lifecycle_haproxy_config       |default(cops_zope_lifecycle_haproxy|default(not only_steps))}) %}
      {% set cops_zope_lifecycle_haproxy_config = r['cops_zope_lifecycle_haproxy_config'] %}
      #
      {% set _ = r.update({'cops_zope_lifecycle_haproxy_registrations': cops_zope_lifecycle_haproxy_registrations|default(cops_zope_lifecycle_haproxy|default(not only_steps))}) %}
      {% set cops_zope_lifecycle_haproxy_registrations = r['cops_zope_lifecycle_haproxy_registrations'] %}
      #
      {% set _ = r.update({'cops_zope_lifecycle_haproxy': ( cops_zope_lifecycle_haproxy_reload or cops_zope_lifecycle_haproxy_config or cops_zope_lifecycle_haproxy_registrations)}) %}
      {% set cops_zope_lifecycle_haproxy = r['cops_zope_lifecycle_haproxy'] %}
      #
      {% set _ = r.update({'only_steps': only_steps|default(False)}) %}
      {% set only_steps = r['only_steps'] %}
      #
      {% set _ = r.update({'cops_zope_s_setup_buildout_smtptimeout':        cops_zope_s_setup_buildout_smtptimeout                                                              |default(cops_zope_s_setup_buildout|default(cops_zope_s_setup|default(cops_zope_lifecycle_app_setup|default(not only_steps))))}) %}
      {% set cops_zope_s_setup_buildout_smtptimeout = r['cops_zope_s_setup_buildout_smtptimeout'] %}
      #
      {% set _ = r.update({'cops_zope_s_setup_buildout_up':        cops_zope_s_setup_buildout_up                                                              |default(cops_zope_s_setup_buildout|default(cops_zope_s_setup|default(cops_zope_lifecycle_app_setup|default(not only_steps))))}) %}
      {% set cops_zope_s_setup_buildout_up = r['cops_zope_s_setup_buildout_up'] %}
      #
      {% set _ = r.update({'cops_zope_s_setup_buildout_buildout':  cops_zope_s_setup_buildout_buildout                                                        |default(cops_zope_s_setup_buildout|default(cops_zope_s_setup|default(cops_zope_lifecycle_app_setup|default(not only_steps))))}) %}
      {% set cops_zope_s_setup_buildout_buildout = r['cops_zope_s_setup_buildout_buildout'] %}
      #
      {% set _ = r.update({'cops_zope_s_setup_buildout_bootstrap': cops_zope_s_setup_buildout_bootstrap                                                       |default(cops_zope_s_setup_buildout|default(cops_zope_s_setup|default(cops_zope_lifecycle_app_setup|default(not only_steps))))}) %}
      {% set cops_zope_s_setup_buildout_bootstrap = r['cops_zope_s_setup_buildout_bootstrap'] %}
      #
      {% set _ = r.update({'cops_zope_s_setup_buildout_configs':   cops_zope_s_setup_buildout_configs                                                         |default(cops_zope_s_setup_buildout|default(cops_zope_s_setup|default(cops_zope_lifecycle_app_setup|default(not only_steps))))}) %}
      {% set cops_zope_s_setup_buildout_configs = r['cops_zope_s_setup_buildout_configs'] %}
      #
      {% set _ = r.update({'cops_zope_s_setup_venv_venv':         cops_zope_s_setup_venv_venv                                                                     |default(cops_zope_s_setup_venv|default(cops_zope_s_setup|default(cops_zope_lifecycle_app_setup|default(not only_steps))))}) %}
      {% set cops_zope_s_setup_venv_venv = r['cops_zope_s_setup_venv_venv'] %}
      #
      {% set _ = r.update({'cops_zope_s_setup_venv_buildpy':      cops_zope_s_setup_venv_buildpy                                                                  |default(cops_zope_s_setup_venv|default(cops_zope_s_setup|default(cops_zope_lifecycle_app_setup|default(not only_steps))))}) %}
      {% set cops_zope_s_setup_venv_buildpy = r['cops_zope_s_setup_venv_buildpy'] %}
      #
      {% set _ = r.update({'cops_zope_s_setup_venv_requirements': cops_zope_s_setup_venv_requirements                                                             |default(cops_zope_s_setup_venv|default(cops_zope_s_setup|default(cops_zope_lifecycle_app_setup|default(not only_steps))))}) %}
      {% set cops_zope_s_setup_venv_requirements = r['cops_zope_s_setup_venv_requirements'] %}
      #
      {% set _ = r.update({'cops_zope_s_setup_front_sync':                   cops_zope_s_setup_front_sync                                                        |default(cops_zope_s_setup_front|default(cops_zope_s_setup|default(cops_zope_lifecycle_app_setup|default(not only_steps))))}) %}
      {% set cops_zope_s_setup_front_sync = r['cops_zope_s_setup_front_sync'] %}
      #
      {% set _ = r.update({'cops_zope_s_setup_front_build_yarn_install':     cops_zope_s_setup_front_build_yarn_install    |default(cops_zope_s_setup_front_build|default(cops_zope_s_setup_front|default(cops_zope_s_setup|default(cops_zope_lifecycle_app_setup|default(not only_steps)))))}) %}
      {% set cops_zope_s_setup_front_build_yarn_install = r['cops_zope_s_setup_front_build_yarn_install'] %}
      #
      {% set _ = r.update({'cops_zope_s_setup_front_build_yarn_extra_steps': cops_zope_s_setup_front_build_yarn_extra_steps|default(cops_zope_s_setup_front_build|default(cops_zope_s_setup_front|default(cops_zope_s_setup|default(cops_zope_lifecycle_app_setup|default(not only_steps)))))}) %}
      {% set cops_zope_s_setup_front_build_yarn_extra_steps = r['cops_zope_s_setup_front_build_yarn_extra_steps'] %}
      #
      {% set _ = r.update({'cops_zope_s_setup_front_build_yarn_build':       cops_zope_s_setup_front_build_yarn_build      |default(cops_zope_s_setup_front_build|default(cops_zope_s_setup_front|default(cops_zope_s_setup|default(cops_zope_lifecycle_app_setup|default(not only_steps)))))}) %}
      {% set cops_zope_s_setup_front_build_yarn_build = r['cops_zope_s_setup_front_build_yarn_build'] %}
      #
      {% set _ = r.update({'cops_zope_s_setup_buildout': ( cops_zope_s_setup_buildout_configs or cops_zope_s_setup_buildout_bootstrap or cops_zope_s_setup_buildout_buildout or cops_zope_s_setup_buildout_up or cops_zope_s_setup_buildout_smtptimeout)}) %}
      {% set cops_zope_s_setup_buildout = r['cops_zope_s_setup_buildout'] %}
      #
      {% set _ = r.update({'cops_zope_s_setup_venv': ( cops_zope_s_setup_venv_venv or cops_zope_s_setup_venv_buildpy or cops_zope_s_setup_venv_requirements)}) %}
      {% set cops_zope_s_setup_venv = r['cops_zope_s_setup_venv'] %}
      #
      {% set _ = r.update({'cops_zope_s_setup_front_build':  (cops_zope_s_setup_front_build_yarn_install or cops_zope_s_setup_front_build_yarn_extra_steps or cops_zope_s_setup_front_build_yarn_build)}) %}
      {% set cops_zope_s_setup_front_build = r['cops_zope_s_setup_front_build'] %}
      #
      {% set _ = r.update({'cops_zope_s_prerequisites_nginxinstall':   cops_zope_s_prerequisites_nginxinstall      |default(cops_zope_s_prerequisites|default(cops_zope_lifecycle_app_prerequisites|default(cops_zope_lifecycle_app_setup|default(not only_steps))))}) %}
      {% set cops_zope_s_prerequisites_nginxinstall = r['cops_zope_s_prerequisites_nginxinstall'] %}
      #
      {% set _ = r.update({'cops_zope_s_prerequisites_ui':   cops_zope_s_prerequisites_ui              |default(cops_zope_s_prerequisites|default(cops_zope_lifecycle_app_prerequisites|default(cops_zope_lifecycle_app_setup|default(not only_steps))))}) %}
      {% set cops_zope_s_prerequisites_ui = r['cops_zope_s_prerequisites_ui'] %}
      #
      {% set _ = r.update({'cops_zope_s_prerequisites_build_pkgs': cops_zope_s_prerequisites_build_pkgs            |default(cops_zope_s_prerequisites|default(cops_zope_lifecycle_app_prerequisites|default(cops_zope_lifecycle_app_setup|default(not only_steps))))}) %}
      {% set cops_zope_s_prerequisites_build_pkgs = r['cops_zope_s_prerequisites_build_pkgs'] %}
      #
      {% set _ = r.update({'cops_zope_s_prerequisites_pkgs': cops_zope_s_prerequisites_pkgs            |default(cops_zope_s_prerequisites|default(cops_zope_lifecycle_app_prerequisites|default(cops_zope_lifecycle_app_setup|default(not only_steps))))}) %}
      {% set cops_zope_s_prerequisites_pkgs = r['cops_zope_s_prerequisites_pkgs'] %}
      #
      {% set _ = r.update({'cops_zope_s_setup_configs':    cops_zope_s_setup_configs                                                                         |default(cops_zope_s_setup|default(cops_zope_lifecycle_app_setup|default(not only_steps)))}) %}
      {% set cops_zope_s_setup_configs = r['cops_zope_s_setup_configs'] %}
      #
      {% set _ = r.update({'cops_zope_s_setup_hosts':      cops_zope_s_setup_hosts                                                                           |default(cops_zope_s_setup|default(cops_zope_lifecycle_app_setup|default(not only_steps)))}) %}
      {% set cops_zope_s_setup_hosts = r['cops_zope_s_setup_hosts'] %}
      #
      {% set _ = r.update({'cops_zope_s_setup_app':        cops_zope_s_setup_app                                                                             |default(cops_zope_s_setup|default(cops_zope_lifecycle_app_setup|default(not only_steps)))}) %}
      {% set cops_zope_s_setup_app = r['cops_zope_s_setup_app'] %}
      #
      {% set _ = r.update({'cops_zope_s_layout_layout':  cops_zope_s_layout_layout|default(cops_zope_s_layout         |default(cops_zope_lifecycle_app_layout|default(cops_zope_s_setup|default(cops_zope_lifecycle_app_setup|default(not only_steps)))))}) %}
      {% set cops_zope_s_layout_layout = r['cops_zope_s_layout_layout'] %}
      #
      {% set _ = r.update({'cops_zope_s_setup_reverse_proxy_dvhost':      cops_zope_s_setup_reverse_proxy_dvhost     |default(cops_zope_s_setup_reverse_proxy|default(cops_zope_s_setup|default(cops_zope_lifecycle_app_setup|default(not only_steps))))}) %}
      {% set cops_zope_s_setup_reverse_proxy_dvhost = r['cops_zope_s_setup_reverse_proxy_dvhost'] %}
      #
      {% set _ = r.update({'cops_zope_s_setup_reverse_proxy_other_vhosts':       cops_zope_s_setup_reverse_proxy_other_vhosts      |default(cops_zope_s_setup_reverse_proxy|default(cops_zope_s_setup|default(cops_zope_lifecycle_app_setup|default(not only_steps))))}) %}
      {% set cops_zope_s_setup_reverse_proxy_other_vhosts = r['cops_zope_s_setup_reverse_proxy_other_vhosts'] %}
      #
      {% set _ = r.update({'cops_zope_s_setup_reverse_proxy_vhost':       cops_zope_s_setup_reverse_proxy_vhost      |default(cops_zope_s_setup_reverse_proxy|default(cops_zope_s_setup|default(cops_zope_lifecycle_app_setup|default(not only_steps))))}) %}
      {% set cops_zope_s_setup_reverse_proxy_vhost = r['cops_zope_s_setup_reverse_proxy_vhost'] %}
      #
      {% set _ = r.update({'cops_zope_s_setup_reverse_proxy_front_vhost': cops_zope_s_setup_reverse_proxy_front_vhost|default(cops_zope_s_setup_reverse_proxy|default(cops_zope_s_setup|default(cops_zope_lifecycle_app_setup|default(not only_steps))))}) %}
      {% set cops_zope_s_setup_reverse_proxy_front_vhost = r['cops_zope_s_setup_reverse_proxy_front_vhost'] %}
      #
      {% set _ = r.update({'cops_zope_s_setup_reverse_proxy_users':       cops_zope_s_setup_reverse_proxy_users      |default(cops_zope_s_setup_reverse_proxy|default(cops_zope_s_setup|default(cops_zope_lifecycle_app_setup|default(not only_steps))))}) %}
      {% set cops_zope_s_setup_reverse_proxy_users = r['cops_zope_s_setup_reverse_proxy_users'] %}
      #
      {% set _ = r.update({'cops_zope_s_reverse_proxy_install':       cops_zope_s_reverse_proxy_install                                              |default(cops_zope_s_reverse_proxy|default(cops_zope_lifecycle_app_setup|default(not only_steps)))}) %}
      {% set cops_zope_s_reverse_proxy_install = r['cops_zope_s_reverse_proxy_install'] %}
      #
      {% set _ = r.update({'cops_zope_s_reverse_proxy_reload':        cops_zope_s_reverse_proxy_reload                                               |default(cops_zope_s_reverse_proxy|default(cops_zope_lifecycle_app_setup|default(not only_steps)))}) %}
      {% set cops_zope_s_reverse_proxy_reload = r['cops_zope_s_reverse_proxy_reload'] %}
      #
      {% set _ = r.update({'cops_zope_s_fixperms_configs':   cops_zope_s_fixperms_configs|default((cops_zope_s_first_fixperms|default(not only_steps)) or (cops_zope_s_end_fixperms|default(not only_steps)))}) %}
      {% set cops_zope_s_fixperms_configs = r['cops_zope_s_fixperms_configs'] %}
      #
      {% set _ = r.update({'cops_zope_s_fixperms_run':       cops_zope_s_fixperms_run    |default((cops_zope_s_first_fixperms|default(not only_steps)) or (cops_zope_s_end_fixperms|default(not only_steps)))}) %}
      {% set cops_zope_s_fixperms_run = r['cops_zope_s_fixperms_run'] %}
      #
      {% set _ = r.update({'cops_zope_s_first_fixperms': cops_zope_s_first_fixperms|default(not only_steps)}) %}
      {% set cops_zope_s_first_fixperms = r['cops_zope_s_first_fixperms'] %}
      #
      {% set _ = r.update({'cops_zope_s_end_fixperms':   cops_zope_s_end_fixperms  |default(not only_steps)}) %}
      {% set cops_zope_s_end_fixperms = r['cops_zope_s_end_fixperms'] %}
      #
      {% set _ = r.update({'cops_zope_s_workers_service':      cops_zope_s_workers_service     |default(cops_zope_s_workers|default(cops_zope_lifecycle_app_setup|default(not only_steps)))}) %}
      {% set cops_zope_s_workers_service = r['cops_zope_s_workers_service'] %}
      #
      {% set _ = r.update({'cops_zope_s_entry_point_configs':  cops_zope_s_entry_point_configs    |default(cops_zope_s_entry_point|default(cops_zope_lifecycle_app_setup|default(not only_steps))) and ansible_virtualization_type in ['docker']}) %}
      {% set cops_zope_s_entry_point_configs = r['cops_zope_s_entry_point_configs'] %}
      #
      {% set _ = r.update({'cops_zope_s_entry_point_services':  cops_zope_s_entry_point_services  |default(cops_zope_s_entry_point|default(cops_zope_lifecycle_app_setup|default(not only_steps))) and ansible_virtualization_type in ['docker']}) %}
      {% set cops_zope_s_entry_point_services = r['cops_zope_s_entry_point_services'] %}
      #
      {% set _ = r.update({'cops_zope_s_users_group': cops_zope_s_users_group |default(cops_zope_s_first_fixperms or cops_zope_s_end_fixperms or cops_zope_lifecycle_app_push_code or cops_zope_s_users|default(cops_zope_lifecycle_app_setup|default(not only_steps)))}) %}
      {% set cops_zope_s_users_group = r['cops_zope_s_users_group'] %}
      #
      {% set _ = r.update({'cops_zope_s_users_user':  cops_zope_s_users_user  |default(cops_zope_s_first_fixperms or cops_zope_s_end_fixperms or cops_zope_lifecycle_app_push_code or cops_zope_s_users|default(cops_zope_lifecycle_app_setup|default(not only_steps)))}) %}
      {% set cops_zope_s_users_user = r['cops_zope_s_users_user'] %}
      #
      {% set _ = r.update({'cops_zope_s_users':          cops_zope_s_users_group or cops_zope_s_users_user}) %}
      {% set cops_zope_s_users = r['cops_zope_s_users'] %}
      #
      {% set _ = r.update({'cops_zope_s_layout':         cops_zope_s_layout_layout}) %}
      {% set cops_zope_s_layout = r['cops_zope_s_layout'] %}
      #
      {% set _ = r.update({'cops_zope_s_prerequisites':  ( cops_zope_s_prerequisites_nginxinstall or cops_zope_s_prerequisites_ui or cops_zope_s_prerequisites_build_pkgs or cops_zope_s_prerequisites_pkgs)}) %}
      {% set cops_zope_s_prerequisites = r['cops_zope_s_prerequisites'] %}
      #
      {% set _ = r.update({'cops_zope_s_workers':        cops_zope_s_workers_service}) %}
      {% set cops_zope_s_workers = r['cops_zope_s_workers'] %}
      #
      {% set _ = r.update({'cops_zope_s_entry_point':    (cops_zope_s_entry_point_configs or cops_zope_s_entry_point_services)}) %}
      {% set cops_zope_s_entry_point = r['cops_zope_s_entry_point'] %}
      #
      {% set _ = r.update({'cops_zope_s_manage_content': cops_zope_s_manage_content|default(cops_zope_lifecycle_app_setup|default(not only_steps))}) %}
      {% set cops_zope_s_manage_content = r['cops_zope_s_manage_content'] %}
      #
      {% set _ = r.update({'cops_zope_s_setup_front':  ( cops_zope_s_setup_front_build or cops_zope_s_setup_front_sync)}) %}
      {% set cops_zope_s_setup_front = r['cops_zope_s_setup_front'] %}
      #
      {% set _ = r.update({'cops_zope_s_setup_reverse_proxy':  ( cops_zope_s_setup_reverse_proxy_dvhost or cops_zope_s_setup_reverse_proxy_other_vhosts or cops_zope_s_setup_reverse_proxy_vhost or cops_zope_s_setup_reverse_proxy_users)}) %}
      {% set cops_zope_s_setup_reverse_proxy = r['cops_zope_s_setup_reverse_proxy'] %}
      #
      {% set _ = r.update({'cops_zope_s_reverse_proxy':  (cops_zope_s_reverse_proxy_reload or cops_zope_s_reverse_proxy_install)}) %}
      {% set cops_zope_s_reverse_proxy = r['cops_zope_s_reverse_proxy'] %}
      #
      {% set _ = r.update({'cops_zope_s_healthchecks':  cops_zope_s_healthchecks  |default(cops_zope_lifecycle_app_setup|default(not only_steps))}) %}
      {% set cops_zope_s_healthchecks = r['cops_zope_s_healthchecks'] %}
      #
      {% set _ = r.update({'cops_zope_s_setup': ( cops_zope_s_setup_configs or cops_zope_s_setup_venv or cops_zope_s_setup_buildout or cops_zope_s_setup_front or cops_zope_s_setup_hosts or cops_zope_s_setup_app or cops_zope_s_setup_reverse_proxy)}) %}
      {% set cops_zope_s_setup = r['cops_zope_s_setup'] %}
      #
      {% set _ = r.update({'cops_zope_lifecycle_app_level_1_steps': ( cops_zope_s_users or cops_zope_s_layout or cops_zope_s_first_fixperms or cops_zope_s_prerequisites or cops_zope_s_setup or cops_zope_s_reverse_proxy or cops_zope_s_workers or cops_zope_s_healthchecks or cops_zope_s_entry_point or cops_zope_s_manage_content or cops_zope_s_end_fixperms)}) %}
      {% set cops_zope_lifecycle_app_level_1_steps = r['cops_zope_lifecycle_app_level_1_steps'] %}
      #
      {% set _ = r.update({'cops_zope_lifecycle_app_setup': cops_zope_lifecycle_app_setup|default( (cops_zope_lifecycle_app|default(False)) or ( cops_zope_lifecycle_app_level_1_steps))}) %}
      {% set cops_zope_lifecycle_app_setup = r['cops_zope_lifecycle_app_setup'] %}
      #
      {% set _ = r.update({'cops_zope_lifecycle_app': cops_zope_lifecycle_app|default(cops_zope_lifecycle_app_push_code or cops_zope_lifecycle_app_setup)}) %}
      {% set cops_zope_lifecycle_app = r['cops_zope_lifecycle_app'] %}
      #
      {% set _ = r.update({'cops_zope_lifecycle_lc_1_steps': (cops_zope_lifecycle_haproxy or cops_zope_lifecycle_app)}) %}
      {% set cops_zope_lifecycle_lc_1_steps = r['cops_zope_lifecycle_lc_1_steps'] %}
      #
      {% set _ = r.update({'cops_zope_s_vars': cops_zope_s_vars|default(cops_zope_lifecycle_lc_1_steps)}) %}
      {% set cops_zope_s_vars = r['cops_zope_s_vars'] %}
      #
      {{ r|to_json }}
