---
# HAPROXY: get the ip of load balancers to configure nginx
# realip module
- hosts: "{{haproxy_servers|default('all')}}"
  gather_facts: yes
  tasks:
    - when: >
         (cops_zope_lifecycle_haproxy|default(false)) and
         (cops_zope_dynamic_haproxy|default(false))
      block: [{setup: {}}]
# APP
- hosts: "{{zope_servers|default('all')}}"
  roles: [corpusops.roles/ansible_plugins]
  gather_facts: yes
  tasks:
  - setup: {}
  - when: ["cops_zope_lifecycle_app|default(true)"]
    tags: ["cops_zope_lifecycle_app"]
    block:
    - include_role: {name: zope_app_vars,  allow_duplicates: false}
  - when: ["cops_zope_lifecycle_app"]
    tags: ["cops_zope_lifecycle_app"]
    block:
    - include_role: {name: zope_push_code, allow_duplicates: false}
    - include_role: {name: zope, allow_duplicates: false}
