---
# generate password on remote box if not found
- when: not vars.get(zopesecret)
  block:
  - set_fact:
      cacheable: false
      cops_get_secret_variable_name: "cops_zope_{{zopesecret}}"
      cops_get_secret_variable_path: "/etc/{{cops_zope_name}}-secrets"
  - name: "Secret generation: {{zopesecret}}"
    include_role:
      name: corpusops.roles/get_secret_variable
    no_log: "{{not (cops_vars_debug|default(false))}}"
  - name: "Update registry with {{zopesecret}}"
    include_jinja_vars:
      content: |
        ---
        {% set p = 'cops_zope_' %}
        {% set _ = vars[p+'vars'].update({zopesecret: vars[p+zopesecret]}) %}
        {{ (vars|copsf_registry(p, namespaced=vars[p+'vars']))[0]|to_json }}
    no_log: "{{not (cops_vars_debug|default(false))}}"
