---
# generate the app vhost(s) before nginx install itself
# as if we have syntax errors, we wont have any chance to regenerate the
# vhost before the general service role will run (syntax check -> deploy KO)
- name: Generate default virtualhost
  include_role:
    name: "corpusops.roles/nginx_default_vhost"
  vars:
    _corpusops_nginx_default_vhost:
      is_default_server: "{{
          cops_zope_vars.default_vhost_is_default_server}}"
      check_config: false
  tags: [cops_zope_s_setup_reverse_proxy_dvhost]
  when: [cops_zope_s_setup_reverse_proxy_dvhost]

- name: Generate APP virtualhost
  include_role: {name: "corpusops.roles/nginx_vhost"}
  vars: {_corpusops_nginx_vhost: "{{cops_zope_vars.nginx}}"}
  tags: [cops_zope_s_setup_reverse_proxy_vhost]
  when: [cops_zope_s_setup_reverse_proxy_vhost]

- name: Generate APP other virtualhost
  include_tasks: _render_vhost.yml
  loop: "{{cops_zope_vars.other_vhosts}}"
  loop_control: {loop_var: other_vhost}
  tags: ["cops_zope_s_setup_reverse_proxy_other_vhosts"]
  when: ["cops_zope_s_setup_reverse_proxy_other_vhosts",
         "cops_zope_other_vhosts|copsf_bool"]

- name: Generate FRONT-APP virtualhost
  include_role: {name: "corpusops.roles/nginx_vhost"}
  vars: {_corpusops_nginx_vhost: "{{cops_zope_vars.front_nginx}}"}
  tags: ["cops_zope_s_setup_reverse_proxy_front_vhost"]
  when: ["cops_zope_s_setup_reverse_proxy_front_vhost and cops_zope_vars.front_domain"]

# Configure http users
- htpasswd:
    path: "{{cops_zope_vars.htpasswd}}"
    name: "{{item.user}}"
    password: "{{item.password}}"
    state: present
  loop: "{{cops_zope_vars.http_users}}"
  when: ["cops_zope_s_setup_reverse_proxy_users and (
            cops_zope_vars.http_users is not none and
            cops_zope_vars.http_users|length > 0)"]
  tags: [cops_zope_s_setup_reverse_proxy_users]
